--test inserts for the table
INSERT INTO FITNESS_POINTS (ID, ACTIVITY, POINTS) VALUES (1, 'walking', 50);
INSERT INTO FITNESS_POINTS (ID, ACTIVITY, POINTS) VALUES (2, 'running', 100);
INSERT INTO FITNESS_POINTS (ID, ACTIVITY, POINTS) VALUES (3, 'dentistCheckup', 100);
INSERT INTO FITNESS_POINTS (ID, ACTIVITY, POINTS) VALUES (4, 'dieticianVisit', 100);
INSERT INTO FITNESS_POINTS (ID, ACTIVITY, POINTS) VALUES (5, 'Other', 100);

--Vitality bands table
INSERT INTO VITALITY_BANDS (ID, LOWER_LIMIT, UPPER_LIMIT, BAND) VALUES (1, 0, 7500, 'Blue');
INSERT INTO VITALITY_BANDS (ID, LOWER_LIMIT, UPPER_LIMIT, BAND) VALUES (2, 7500, 25000, 'Bronze');
INSERT INTO VITALITY_BANDS (ID, LOWER_LIMIT, UPPER_LIMIT, BAND) VALUES (3, 25000, 40000, 'Gold');
INSERT INTO VITALITY_BANDS (ID, LOWER_LIMIT, UPPER_LIMIT, BAND) VALUES (4, 50000, 5000, 'Silver');
INSERT INTO VITALITY_BANDS (ID, LOWER_LIMIT, UPPER_LIMIT, BAND) VALUES (5, 50000, 200000, 'Diamond');


INSERT INTO HEALTHY_FOODS(ID, LOWER_LIMIT, UPPER_LIMIT, POINTS) VALUES(1,0,500, 1572);
INSERT INTO HEALTHY_FOODS(ID, LOWER_LIMIT, UPPER_LIMIT, POINTS) VALUES(2,501,1000, 4614);
INSERT INTO HEALTHY_FOODS(ID, LOWER_LIMIT, UPPER_LIMIT, POINTS) VALUES(3,1001,1500, 7681);
INSERT INTO HEALTHY_FOODS(ID, LOWER_LIMIT, UPPER_LIMIT, POINTS) VALUES(4,1501,2000, 10818);
INSERT INTO HEALTHY_FOODS(ID, LOWER_LIMIT, UPPER_LIMIT, POINTS) VALUES(5,2001,2147483647, 12000);

-- TODO: Add in the different types of health check points you can get

INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (1, "Vitality_Age", 1500)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (2, "Mental_Wellbeing", 500)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (3, "Golf_Played", 100)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (4, "Flu_Vaccine", 1000)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (5, "Initial_HIV_Test", 7500)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (6, "Annual_HIV_Test", 1000)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (7, "Pap_Smear", 2500)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (8, "Mammogram", 2500)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (9, "Colonoscopy", 2500)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (10, "Dental_Check", 1000)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (11, "Glaucoma_Screening", 2500)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (12, "Managing_Chronic_Condition", 2500)
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (13, "Blood_Pressure", )
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (14, "Blood_Glucose", )
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (15, "Cholesterol", )
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (16, "Weight_Assesment", )
INSERT INTO HEALTH_CHECKS(ID, HEALTH_CHECK_NAME, POINTS) VALUES (17, "Non_Smokers_Declaration",)