--test inserts for the table
INSERT INTO VITALITY_POINTS (ID, ACTIVITY, POINTS) VALUES (1, 'walking', 50);
INSERT INTO VITALITY_POINTS (ID, ACTIVITY, POINTS) VALUES (2, 'running', 100);
INSERT INTO VITALITY_POINTS (ID, ACTIVITY, POINTS) VALUES (3, 'dentistCheckup', 100);
INSERT INTO VITALITY_POINTS (ID, ACTIVITY, POINTS) VALUES (4, 'dieticianVisit', 100);
INSERT INTO VITALITY_POINTS (ID, ACTIVITY, POINTS) VALUES (5, 'Other', 100);